---
apiVersion: v1
kind: ImageStream
metadata:
  name: jenkins-agent-maven-35-rhel7-custom
spec: {}
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: custom-jenkins-agent-maven
spec:
  source:
    git:
      uri: https://github.com/nishipy/jenkins-agent-custom
      ref: main
    type: Git
    secrets:
    - secret:
        name: etc-pki-entitlement
      destinationDir: etc-pki-entitlement
  strategy: 
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  output:
    to:
      kind: ImageStreamTag
      name: jenkins-agent-maven-35-rhel7-custom:latest